/**
 * The 76-feature pipeline from tech_assignment_challenge_1/scripts/features.py,
 * ported number for number:
 *   [0..63]  per-frame ambient normalization: (pixel - median) / max(std, 0.1)
 *   [64]     row_max        [65] row_range
 *   [66]     count > median+3   [67] count > median+5
 *   [68..75] spatial: gradient, largest_blob (BFS), quadrant_var, center_vs_edge,
 *            row_profile_std, col_profile_std, hot_centroid_r, hot_pixel_ratio
 * Tested against fixtures generated by running the real features.py (pnpm sync-demos esp32).
 */

export const N_FEATURES = 76;

export function median64(px: Float32Array | number[]): number {
  const s = Array.from(px).sort((a, b) => a - b);
  return (s[31] + s[32]) / 2;
}

function std(px: ArrayLike<number>): number {
  let m = 0;
  for (let i = 0; i < px.length; i++) m += px[i];
  m /= px.length;
  let v = 0;
  for (let i = 0; i < px.length; i++) v += (px[i] - m) * (px[i] - m);
  return Math.sqrt(v / px.length); // population std, like np.std
}

/**
 * BFS largest connected component of pixels strictly greater than threshold,
 * 4-connectivity on the 8x8 grid. Exact port of _largest_connected_component.
 * Optionally records the visit order + membership for the animated flood.
 */
export function largestBlob(
  grid: ArrayLike<number>,
  threshold: number,
  trace?: { order: number[]; inLargest: boolean[] },
): number {
  const visited = new Array<boolean>(64).fill(false);
  let largest = 0;
  let largestCells: number[] = [];
  const allOrder: number[] = [];
  for (let r = 0; r < 8; r++) {
    for (let c = 0; c < 8; c++) {
      const idx = r * 8 + c;
      if (visited[idx] || grid[idx] <= threshold) continue;
      const cells: number[] = [];
      const q: number[] = [idx];
      visited[idx] = true;
      while (q.length) {
        const cur = q.shift()!;
        cells.push(cur);
        allOrder.push(cur);
        const cr = Math.floor(cur / 8);
        const cc = cur % 8;
        const nbrs = [
          [cr - 1, cc],
          [cr + 1, cc],
          [cr, cc - 1],
          [cr, cc + 1],
        ];
        for (const [nr, nc] of nbrs) {
          if (nr < 0 || nr >= 8 || nc < 0 || nc >= 8) continue;
          const ni = nr * 8 + nc;
          if (!visited[ni] && grid[ni] > threshold) {
            visited[ni] = true;
            q.push(ni);
          }
        }
      }
      if (cells.length > largest) {
        largest = cells.length;
        largestCells = cells;
      }
    }
  }
  if (trace) {
    trace.order = allOrder;
    trace.inLargest = new Array(64).fill(false);
    for (const i of largestCells) trace.inLargest[i] = true;
  }
  return largest;
}

/** compute_spatial_features() — returns the 8 spatial features. */
export function spatialFeatures(px: ArrayLike<number>): number[] {
  const grid = Array.from({ length: 8 }, (_, r) => Array.from({ length: 8 }, (_, c) => px[r * 8 + c]));
  const med = median64(Array.from(px as ArrayLike<number>) as number[]);
  const threshold = med + 3.0;

  // spatial_gradient
  let h = 0;
  let v = 0;
  for (let r = 0; r < 8; r++) for (let c = 0; c < 7; c++) h += Math.abs(grid[r][c + 1] - grid[r][c]);
  for (let r = 0; r < 7; r++) for (let c = 0; c < 8; c++) v += Math.abs(grid[r + 1][c] - grid[r][c]);
  const spatialGradient = (h / 56 + v / 56) / 2;

  const blob = largestBlob(px, threshold);

  // quadrant_var — population variance of the four 4x4 quadrant means
  const qm: number[] = [];
  for (const [r0, c0] of [
    [0, 0],
    [0, 4],
    [4, 0],
    [4, 4],
  ]) {
    let s = 0;
    for (let r = r0; r < r0 + 4; r++) for (let c = c0; c < c0 + 4; c++) s += grid[r][c];
    qm.push(s / 16);
  }
  const qMean = (qm[0] + qm[1] + qm[2] + qm[3]) / 4;
  const quadrantVar = qm.reduce((a, m) => a + (m - qMean) * (m - qMean), 0) / 4;

  // center_vs_edge
  let centerSum = 0;
  let total = 0;
  for (let i = 0; i < 64; i++) total += px[i];
  for (let r = 2; r < 6; r++) for (let c = 2; c < 6; c++) centerSum += grid[r][c];
  const centerVsEdge = centerSum / 16 - (total - centerSum) / 48;

  // row/col profile std (of the maxima)
  const rowMaxs = grid.map((row) => Math.max(...row));
  const colMaxs = Array.from({ length: 8 }, (_, c) => Math.max(...grid.map((row) => row[c])));
  const rowProfileStd = std(rowMaxs);
  const colProfileStd = std(colMaxs);

  // hot centroid / ratio
  let hot = 0;
  let sr = 0;
  let sc = 0;
  for (let r = 0; r < 8; r++)
    for (let c = 0; c < 8; c++)
      if (grid[r][c] > threshold) {
        hot++;
        sr += r;
        sc += c;
      }
  let hotCentroidR = 0;
  let hotPixelRatio = 0;
  if (hot > 0) {
    const cr = sr / hot - 3.5;
    const cc = sc / hot - 3.5;
    hotCentroidR = Math.sqrt(cr * cr + cc * cc);
    hotPixelRatio = hot / 64;
  }

  return [spatialGradient, blob, quadrantVar, centerVsEdge, rowProfileStd, colProfileStd, hotCentroidR, hotPixelRatio];
}

/** engineer_features() for a single frame — 76 values in the training order. */
export function engineerFeatures(px: ArrayLike<number>): Float32Array {
  const med = median64(Array.from(px as ArrayLike<number>) as number[]);
  const sd = Math.max(std(px), 0.1);
  const out = new Float32Array(N_FEATURES);
  let max = -Infinity;
  let min = Infinity;
  let c3 = 0;
  let c5 = 0;
  for (let i = 0; i < 64; i++) {
    const p = px[i];
    out[i] = (p - med) / sd;
    if (p > max) max = p;
    if (p < min) min = p;
    if (p > med + 3.0) c3++;
    if (p > med + 5.0) c5++;
  }
  out[64] = max;
  out[65] = max - min;
  out[66] = c3;
  out[67] = c5;
  const sp = spatialFeatures(px);
  for (let i = 0; i < 8; i++) out[68 + i] = sp[i];
  return out;
}

/** StandardScaler transform with the deployed mean/scale (model_params.h). */
export function scale(x: Float32Array, mean: number[], sc: number[]): Float32Array {
  const out = new Float32Array(x.length);
  for (let i = 0; i < x.length; i++) out[i] = (x[i] - mean[i]) / sc[i];
  return out;
}
