/**
 * The TS ports must reproduce the real pipeline:
 *  - features.ts vs fixtures from running David's features.py
 *  - net.ts float path vs the Keras model, int8 path vs the TFLite interpreter
 * Fixtures are generated by `pnpm sync-demos esp32`.
 */
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { engineerFeatures, largestBlob, N_FEATURES, scale } from "@/demos/esp32/core/features";
import { forwardFloat, forwardInt8, quantizeInput, type ModelJson } from "@/demos/esp32/core/net";

function fx<T>(name: string): T {
  return JSON.parse(fs.readFileSync(path.join(process.cwd(), "tests", "fixtures", name), "utf8")) as T;
}

function pub<T>(name: string): T {
  return JSON.parse(
    fs.readFileSync(path.join(process.cwd(), "public", "demos", "esp32", name), "utf8"),
  ) as T;
}

interface FeaturesFx {
  nFeatures: number;
  cases: { px: number[]; features: number[]; label: number }[];
}

interface NetFx {
  cases: {
    xScaled: number[];
    floatProb: number;
    inputQ: number[];
    layersQ: number[][];
    outQ: number;
    label: number;
  }[];
}

describe("features.ts vs features.py", () => {
  const f = fx<FeaturesFx>("esp32-features.json");

  it("pipeline is 76 features wide", () => {
    expect(f.nFeatures).toBe(N_FEATURES);
  });

  it("all 76 features match the Python pipeline on real frames", () => {
    for (const c of f.cases) {
      const got = engineerFeatures(c.px);
      for (let i = 0; i < N_FEATURES; i++) {
        // float32 in Python vs float64 here — tolerance covers the dtype gap
        expect(Math.abs(got[i] - c.features[i])).toBeLessThan(2e-3);
      }
      // the blob count is an integer and must be exact
      expect(got[69]).toBe(c.features[69]);
    }
  });

  it("BFS matches the test_features.py L-shape case", () => {
    const grid = new Array(64).fill(0);
    grid[0] = 10;
    grid[1] = 10;
    grid[8] = 10;
    grid[16] = 10;
    grid[5 * 8 + 5] = 10;
    expect(largestBlob(grid, 5.0)).toBe(4);
  });
});

describe("net.ts vs Keras / TFLite interpreter", () => {
  const model = pub<ModelJson>("model.json");
  const f = fx<NetFx>("esp32-net.json");

  it("model.json has the deployed architecture and the 6,672-byte flatbuffer", () => {
    expect(model.arch).toEqual([76, 32, 16, 1]);
    expect(model.quantLayers.length).toBe(3);
    expect(model.floatLayers.length).toBe(3);
    expect(model.tfliteBytes).toBe(6672);
  });

  it("float32 forward pass matches Keras on 50 frames", () => {
    for (const c of f.cases) {
      const { prob } = forwardFloat(model, c.xScaled);
      expect(Math.abs(prob - c.floatProb)).toBeLessThan(1e-3);
    }
  });

  it("input quantization matches the interpreter exactly", () => {
    for (const c of f.cases) {
      expect(quantizeInput(model, c.xScaled)).toEqual(c.inputQ);
    }
  });

  it("int8 kernels match the interpreter within 1 quantum everywhere", () => {
    let exactOut = 0;
    for (const c of f.cases) {
      const tr = forwardInt8(model, c.xScaled);
      for (let l = 0; l < c.layersQ.length; l++) {
        for (let i = 0; i < c.layersQ[l].length; i++) {
          expect(Math.abs(tr.layersQ[l][i] - c.layersQ[l][i])).toBeLessThanOrEqual(1);
        }
      }
      expect(Math.abs(tr.outQ - c.outQ)).toBeLessThanOrEqual(1);
      if (tr.outQ === c.outQ) exactOut++;
    }
    // the vast majority should be bit-exact, not just within tolerance
    expect(exactOut / f.cases.length).toBeGreaterThan(0.9);
  });

  it("float and int8 agree on the verdict for almost every frame", () => {
    let agree = 0;
    for (const c of f.cases) {
      const pf = forwardFloat(model, c.xScaled).prob > 0.5;
      const pq = forwardInt8(model, c.xScaled).prob > 0.5;
      if (pf === pq) agree++;
    }
    expect(agree / f.cases.length).toBeGreaterThan(0.9);
  });

  it("the scaler round-trips model_params.h", () => {
    const x = new Float32Array(model.scalerMean.length).fill(1);
    const s = scale(x, model.scalerMean, model.scalerScale);
    for (let i = 0; i < s.length; i++) {
      expect(Math.abs(s[i] - (1 - model.scalerMean[i]) / model.scalerScale[i])).toBeLessThan(1e-6);
    }
  });
});
