/**
 * The p300 decode.ts port must reproduce the notebook's own decoding functions
 * (fixture from `pnpm sync-demos p300`, generated by running the Python
 * originals copied into p300_prep.py). Fixture pools are singletons by
 * construction, so the tie-break RNG never influences the expected letter.
 */
import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  CHAR_SET,
  LIST_MATRIX,
  breakTies,
  charPredictions,
  checkIntersect,
  checkLetter,
  decodeCharacter,
  dictPredictions,
  meanPredictions,
  roundArgmax,
} from "@/demos/p300/core/decode";

interface FxCase {
  nEpoch: number;
  predictions: number[];
  stimulus: number[];
  mean: number[];
  rounded: number[];
  candidates: string[];
  dict: Record<string, number>;
  letter: string;
  poolLen: number;
}
interface Fx {
  cases: FxCase[];
  hand: { sorted: number[]; rounded: number[]; candidates: string[] };
}

const fx: Fx = JSON.parse(
  fs.readFileSync(path.join(__dirname, "fixtures", "p300-decode.json"), "utf8"),
);

describe("speller matrix", () => {
  it("is the notebook's A-Z 1-9 _ layout", () => {
    expect(CHAR_SET).toHaveLength(36);
    expect(LIST_MATRIX).toHaveLength(12);
    // column 4 (stim code 4) holds D J P V 2 8; row 3 (stim code 9) holds M N O P Q R
    expect(LIST_MATRIX[3]).toEqual(["D", "J", "P", "V", "2", "8"]);
    expect(LIST_MATRIX[8]).toEqual(["M", "N", "O", "P", "Q", "R"]);
    expect(checkLetter(4, 9)).toBe("P");
    expect(checkLetter(4, 4)).toBeNull();
    expect(checkLetter(9, 12)).toBeNull();
  });
});

describe("decode fixture (notebook originals)", () => {
  it("has cases", () => {
    expect(fx.cases.length).toBeGreaterThanOrEqual(20);
  });

  for (const [i, c] of fx.cases.entries()) {
    it(`case ${i} (nEpoch=${c.nEpoch})`, () => {
      const mean = meanPredictions(c.predictions, c.stimulus, c.nEpoch);
      for (let k = 0; k < 12; k++) expect(mean[k]).toBeCloseTo(c.mean[k], 5);
      const rounded = roundArgmax(mean);
      expect(rounded).toEqual(c.rounded);
      expect(charPredictions(rounded)).toEqual(c.candidates);
      const dict = dictPredictions(c.predictions, c.stimulus, c.nEpoch);
      const expected = new Map(Object.entries(c.dict));
      expect(dict.size).toBe(expected.size);
      for (const [k, v] of expected) expect(dict.get(k)!).toBeCloseTo(v, 5);
      expect(c.poolLen).toBe(1); // RNG-independent by construction
      const { letter } = decodeCharacter(c.predictions, c.stimulus, c.nEpoch, () => 0);
      expect(letter).toBe(c.letter);
    });
  }

  it("hand tie case matches", () => {
    const rounded = roundArgmax(fx.hand.sorted);
    expect(rounded).toEqual(fx.hand.rounded);
    expect(charPredictions(rounded)).toEqual(fx.hand.candidates);
  });

  it("breakTies falls back to candidates when the dict is empty", () => {
    expect(breakTies(["A", "B"], new Map(), () => 0)).toBe("A");
    expect(breakTies(["A", "B"], new Map(), () => 0.99)).toBe("B");
    expect(breakTies([], new Map(), () => 0)).toBeNull();
  });

  it("checkIntersect finds all pairwise letters", () => {
    // codes 1 (col A G M S Y 5) and 7 (row A B C D E F) intersect at A
    expect(checkIntersect([1, 7])).toEqual(["A"]);
    // two cols + one row: two intersections
    expect(checkIntersect([1, 2, 7]).sort()).toEqual(["A", "B"]);
  });
});
