/**
 * TS ports of the evaluation math in DavidBrin/Semi-supervised-image-model's
 * CrossTeachingTraining.py (compute_metrics, get_confidence_and_labels, and
 * evaluate_ensemble's logit averaging). Fixture-tested against the Python
 * pipeline in tests/crossteach-core.test.ts (tests/fixtures/crossteach-core.json,
 * generated by scripts/demos/crossteach_prep.py from the shipped assets).
 */

export const NUM_CLASSES = 3;
export const CONF_THRESHOLD = 0.75;

export interface SegMetrics {
  dice: number;
  iou: number;
  pixelAccuracy: number;
}

/** Macro dice/iou + pixel accuracy over label maps (the repo's compute_metrics). */
export function computeMetrics(
  pred: ArrayLike<number>,
  target: ArrayLike<number>,
  numClasses: number = NUM_CLASSES,
): SegMetrics {
  const n = pred.length;
  if (target.length !== n) throw new Error("computeMetrics: length mismatch");
  let correct = 0;
  const inter = new Float64Array(numClasses);
  const predSum = new Float64Array(numClasses);
  const targetSum = new Float64Array(numClasses);
  for (let i = 0; i < n; i++) {
    const p = pred[i];
    const t = target[i];
    if (p === t) correct++;
    predSum[p]++;
    targetSum[t]++;
    if (p === t) inter[p]++;
  }
  let dice = 0;
  let iou = 0;
  for (let c = 0; c < numClasses; c++) {
    const union = predSum[c] + targetSum[c] - inter[c];
    dice += (2 * inter[c] + 1e-6) / (predSum[c] + targetSum[c] + 1e-6);
    iou += (inter[c] + 1e-6) / (union + 1e-6);
  }
  return {
    dice: dice / numClasses,
    iou: iou / numClasses,
    pixelAccuracy: correct / n,
  };
}

/** Image-level confidence: mean of the per-pixel max-softmax map (0..1). */
export function imageConfidence(conf: ArrayLike<number>): number {
  let s = 0;
  for (let i = 0; i < conf.length; i++) s += conf[i];
  return s / conf.length;
}

/** The redesign's gate: an image only teaches if its mean confidence clears tau. */
export function gatePasses(meanConfidence: number, threshold: number = CONF_THRESHOLD): boolean {
  return meanConfidence >= threshold;
}

/**
 * evaluate_ensemble's core: average two logit tensors [C][H][W] (the ViT's
 * already upsampled to the U-Net grid) and argmax per pixel.
 */
export function ensembleArgmax(
  unetLogits: number[][][],
  vitLogits: number[][][],
): number[][] {
  const C = unetLogits.length;
  const H = unetLogits[0].length;
  const W = unetLogits[0][0].length;
  const out: number[][] = [];
  for (let y = 0; y < H; y++) {
    const row: number[] = [];
    for (let x = 0; x < W; x++) {
      let best = 0;
      let bestV = -Infinity;
      for (let c = 0; c < C; c++) {
        const v = (unetLogits[c][y][x] + vitLogits[c][y][x]) / 2;
        if (v > bestV) {
          bestV = v;
          best = c;
        }
      }
      row.push(best);
    }
    out.push(row);
  }
  return out;
}
