import type { SiteManifest } from "@/lib/types";

const site: SiteManifest = {
  project: "crossteach",
  kind: "demo",
  displayName: "Cross-Teaching Segmentation",
  fakeDomain: "crossteach.davids.net",
  liveUrl: "/demos/crossteach",
  tagline: "A U-Net and a ViT swap pseudo-labels: watch semi-supervised segmentation work with its real trained checkpoints.",
  description:
    "Interactive demo of the DTU 02456 Group 9 project (fall 2025) and David's 2026 Oxford-IIIT Pet redesign: semi-supervised cross-teaching, where a U-Net (ResNet-34, 512px) and a Vision Transformer (ViT-B/16, 224px) grade each other's predictions on unlabeled images. Every prediction, confidence map, encoder activation and attention rollout on the page was generated by running the four real checkpoints from the public GitHub repo; the training curves are the committed per-epoch metrics. Includes the original micro-CT story (Dice 0.49 to 0.97 with 22 labeled slices), the honest Oxford-Pet verdict (a wash at 590 labels), the never-run CrossDetection.py detector, and a live learning ladder through the course's notebooks.",
  accentColor: "#14B8A6",
  favicon: "\u{1F43E}",
  techStack: [
    "PyTorch", "segmentation-models-pytorch", "timm (ViT-B/16)", "TensorFlow Datasets",
    "Oxford-IIIT Pet", "TypeScript", "Canvas",
  ],
  needsDatabase: false,
  deepLinks: [
    {
      path: "#exchange",
      title: "The pseudo-label exchange",
      snippet:
        "Pick a pet, compare supervised vs cross-taught predictions from the real checkpoints, dim pixels below the confidence slider, and press teach to watch pseudo-labels cross the resolution gap.",
      keywords: ["pseudo-labels", "confidence threshold", "consistency loss", "semi-supervised", "cross-teaching"],
    },
    {
      path: "#training",
      title: "Training replay + two verdicts",
      snippet:
        "The committed per-epoch curves: warmup holds the exchange off for 2 epochs, then the confident-image ratio jumps to 1.0. Final table for Oxford Pet, and the report's micro-CT numbers (0.49 to 0.97) with real slices.",
      keywords: ["dice", "training curves", "warmup", "micro-ct", "porosity", "results"],
    },
    {
      path: "#architectures",
      title: "U-Net vs ViT, inside",
      snippet:
        "Real encoder activations stage by stage, the image tiled into 196 patches, and attention rollout from the shipped ViT checkpoint - hover a patch to see where it looks. Plus CrossDetection.py, the deeper detector pair that never ran.",
      keywords: ["u-net", "vision transformer", "attention rollout", "skip connections", "faster r-cnn", "receptive field"],
    },
    {
      path: "#ladder",
      title: "The learning ladder",
      snippet:
        "DTU 02456 week by week: live autodiff and half-moon training in TypeScript, then explained-and-visualized cards for MNIST, CIFAR-10 CNNs, transfer, RNNs, autoencoders, VAEs and GANs.",
      keywords: ["autodiff", "feed-forward", "cnn", "rnn", "vae", "gan", "course notebooks"],
    },
  ],
  images: [],
  videos: [],
  keywords: [
    "cross-teaching", "semi-supervised segmentation", "u-net", "vision transformer",
    "pseudo-labels", "dtu", "deep learning", "micro-ct", "oxford-iiit pet",
  ],
  knowledgePanel: {
    type: "Group project demo",
    facts: {
      Course: "02456 Deep Learning, DTU, fall 2025",
      Group: "Group 9 (4 members)",
      Method: "cross-teaching U-Net (512) + ViT (224); confidence-gated pseudo-labels",
      Result: "micro-CT Dice 0.49 to 0.97 with 22 labels; Oxford-Pet redesign a wash at 590",
      "On this page": "the repo's 4 real checkpoints run over held-out images; committed training curves",
    },
  },
  docs: { readme: true, spec: false, decisions: false },
};

export default site;
