import type { DemoMeta } from "@/lib/demos";

const T = "demos/tinyml_esp32_raw";
const F = "demos/esp32_iot_fastapi_raw";

const meta: DemoMeta = {
  slug: "esp32",
  theme: { bg: "#fdf6ee", panel: "#f9ecd9" }, // warm amber — a thermal camera's page
  what: "an 8×8 thermal camera's full journey: transports, a class dataset, 76 features, a 6,672-byte INT8 brain",
  why: "TinyML only clicks when you can watch every stage of the pipeline run on a real frame",
  when: "ECE 140 (UC San Diego), winter 2026",
  story: [
    {
      title: "One sensor, a whole quarter",
      body:
        "ECE 140's hardware track kept returning to the same part: an AMG8833 thermal camera — 64 pixels of temperature at about 10 fps — wired to an ESP32-S3. Week after week the assignments changed what happened to those 64 numbers: print them, publish them, collect them, learn from them. This page replays that arc on real frames from the class dataset.",
      anchor: "#camera",
    },
    {
      title: "Serial, then MQTT, then WebSockets",
      body:
        "The frames first crawled up a USB cable as CSV lines (and the tutorial's delay() showed up as gaps in the stream). Then MQTT: the ESP32 publishes to a broker topic and a Python viewer subscribes — plus a request/response challenge where the laptop asks for one frame on a request topic and the ESP32 answers on a response topic. Finally WebSockets, so a browser labeling UI could stream frames both ways while you tapped p or e to label them.",
      anchor: "#transport",
    },
    {
      title: "22,054 frames from the whole class",
      body:
        "Everyone's labeled frames landed in one dataset: 22,054 frames, 50.6% empty / 49.4% present — nearly balanced. The dataset-explorer analysis found a max-pixel-temperature boundary around 26–28 °C between the classes, and used exactly that to hunt likely mislabeled frames ('present' with max under 26 °C). Its histogram and mislabeled-frame figures are reproduced here.",
      anchor: "#camera",
    },
    {
      title: "76 features, one BFS",
      body:
        "A max-temperature threshold works until the room warms up. The feature pipeline normalizes each frame against its own median and std, then adds intensity stats and eight spatial features — the star being the largest connected blob of pixels more than 3 °C above the median, found by breadth-first search: a person is one warm contiguous region, noise isn't. Watch the flood fill find it, cell by cell.",
      anchor: "#features",
    },
    {
      title: "Train, quantize, deploy — 6,672 bytes",
      body:
        "A dense 76→32→16→1 network with L2 0.005, validated with GroupKFold by student so the model is never graded on a person it trained on. Then INT8 quantization: the 61,863-byte Keras model becomes a 6,672-byte TFLite flatbuffer, flashed as a C array. The panel runs float32 and INT8 side by side on the live frame — activations, scales, zero-points — and the ESP32's runInference loop (quantize → invoke → dequantize) classifies the stream.",
      anchor: "#tinyml",
    },
    {
      title: "Side quest: the WiFi net-map",
      body:
        "One week the ESP32 scanned WiFi instead: scan results POSTed to a FastAPI endpoint, rendered as a force-directed graph of SSIDs by channel and signal strength. The scans here are synthetic — real SSIDs and BSSIDs would map the neighbors — but the pipeline is the real one.",
      anchor: "#netmap",
    },
    {
      title: "Rebuilt for this page (2026-08-31)",
      body:
        "The TypeScript ports (features, BFS, the INT8 kernels) were written with AI coding tools and tested against the real pipeline: fixtures generated by running David's features.py and the deployed model.tflite through the TFLite interpreter at build time. Privacy: contributor IDs are salted-hash prefixes, only ~500 of the 17,610 frames ship, and an 8×8 thermal frame identifies no one. One correction to the plan: the spec said 65 features — the deployed assignment pipeline is 76, and 76 is what runs here.",
    },
  ],
  sources: [
    { name: "features.ts", path: "src/demos/esp32/core/features.ts", lang: "ts", note: "TS port of the 76-feature pipeline, BFS blob included. Tested against features.py fixtures." },
    { name: "net.ts", path: "src/demos/esp32/core/net.ts", lang: "ts", note: "Float32 forward pass + faithful TFLite INT8 kernels (per-tensor affine, int32 accumulate, fused ReLU). Tested against the real interpreter." },
    { name: "features.py", path: `${T}/tech_assignment_challenge_1/scripts/features.py`, lang: "python", note: "David's completed feature engineering — ambient normalization, intensity stats, the BFS largest-blob, extra-credit centroid features." },
    { name: "train.py", path: `${T}/tech_assignment_challenge_2/scripts/train.py`, lang: "python", note: "David's completed training: StandardScaler, Dense 32/16/1 with L2 0.005, GroupKFold by student, EarlyStopping + ReduceLROnPlateau." },
    { name: "export.py", path: `${T}/tech_assignment_challenge_2/scripts/export.py`, lang: "python", note: "David's completed INT8 export: representative dataset, TFLite converter, C headers (model_data.h / model_params.h)." },
    { name: "main.cpp", path: `${T}/tech_assignment_challenge_2/esp32/src/main.cpp`, lang: "cpp", note: "The on-device inference loop: read AMG8833, engineer features, scale, quantize, invoke TFLite Micro, dequantize." },
    { name: "ECE140_MQTT.cpp", path: `${F}/ta3_mqtt_thermal_camera/challenge1_mqtt_thermal/esp32/src/ECE140_MQTT.cpp`, lang: "cpp", note: "Course-provided MQTT helper class (ECE 140 staff) — shown for the transport panel's reconnect behavior." },
    { name: "thermal_controller.py", path: `${F}/ta3_mqtt_thermal_camera/challenge2_mqtt_request/python/thermal_controller.py`, lang: "python", note: "The MQTT request/response controller: ask for a frame, get a frame." },
    { name: "wifiscrape_webserver.py", path: `${F}/ta4_fastapi_wifi_netmap/challenge1_fastapi_netmap/python/wifiscrape_webserver.py`, lang: "python", note: "FastAPI endpoints behind the net-map: POST /get_netscan, GET /netmap_graph." },
    { name: "prep script", path: "scripts/demos/esp32_prep.py", lang: "python", note: "Build-time prep: anonymized frame subset, weights + quant params out of model.tflite, re-run training curves, fixtures for the TS ports." },
  ],
  sourceFooter:
    "Course scaffolding (ECE140_WIFI/MQTT helpers, starter TODOs) by ECE 140 staff; completions, tests, and the deployed model are David's. Class dataset contributors are anonymized (salted hashes); WiFi scans are synthetic. TS ports written with AI coding tools for this page, 2026-08-31.",
};

export default meta;
