/**
 * FIR filtering for the Brainwave lab — TypeScript ports of what the DSP notebook calls.
 *
 *   neurodsp.filt.filter_signal(sig, fs, 'lowpass', f_hi, n_seconds=…, remove_edges=False)
 *   → scipy.signal.firwin(filt_len, f_hi, fs=fs)  +  np.convolve(sig, coefs, 'same')
 *
 * Every function here is checked against SciPy's output in tests/nocturnal-eeg.test.ts
 * (fixture generated by scripts/demos/nocturnal_prep.py).  Nothing is approximated: the
 * window, the scaling and the convolution centring all follow the Python line for line.
 */

/** Hamming window, symmetric (scipy.signal.get_window('hamming', N, fftbins=False)). */
export function hamming(n: number): Float64Array {
  const w = new Float64Array(n);
  if (n === 1) {
    w[0] = 1;
    return w;
  }
  for (let i = 0; i < n; i++) w[i] = 0.54 - 0.46 * Math.cos((2 * Math.PI * i) / (n - 1));
  return w;
}

/** Normalised sinc, sin(πx)/(πx), as numpy.sinc. */
function sinc(x: number): number {
  if (x === 0) return 1;
  const px = Math.PI * x;
  return Math.sin(px) / px;
}

/**
 * Port of scipy.signal.firwin(numtaps, cutoff, fs=fs, pass_zero=passZero, window='hamming', scale=True).
 *
 * `cutoff` is one edge (lowpass / highpass) or `[lo, hi]` (bandstop when passZero, bandpass
 * otherwise), in Hz.  Windowed-sinc design: sum the ideal responses of each pass band, apply
 * the window, then scale so the gain is exactly 1 at DC (lowpass / bandstop), at Nyquist
 * (highpass) or at the band centre (bandpass).
 */
export function firwin(numtaps: number, cutoff: number | [number, number], fs: number, passZero = true): Float64Array {
  const nyq = fs / 2;
  const edges = (Array.isArray(cutoff) ? cutoff : [cutoff]).map((c) => c / nyq);
  for (const e of edges) {
    if (!(e > 0 && e < 1)) throw new Error("firwin: cutoff must lie strictly between 0 and fs/2");
  }
  // scipy: pass_nyquist = bool(cutoff.size & 1) ^ pass_zero
  const passNyquist = (edges.length & 1) === 1 !== passZero;
  if (passNyquist && numtaps % 2 === 0) {
    throw new Error("firwin: a filter passing Nyquist needs an odd number of taps");
  }
  const bands: number[] = [...(passZero ? [0] : []), ...edges, ...(passNyquist ? [1] : [])];

  const alpha = 0.5 * (numtaps - 1);
  const h = new Float64Array(numtaps);
  for (let b = 0; b < bands.length; b += 2) {
    const left = bands[b];
    const right = bands[b + 1];
    for (let i = 0; i < numtaps; i++) {
      const m = i - alpha;
      h[i] += right * sinc(right * m) - left * sinc(left * m);
    }
  }

  const win = hamming(numtaps);
  for (let i = 0; i < numtaps; i++) h[i] *= win[i];

  // scale=True: unity gain at the centre of the first pass band
  let scaleFreq: number;
  if (bands[0] === 0) scaleFreq = 0;
  else if (bands[1] === 1) scaleFreq = 1;
  else scaleFreq = (bands[0] + bands[1]) / 2;
  let s = 0;
  for (let i = 0; i < numtaps; i++) s += h[i] * Math.cos(Math.PI * (i - alpha) * scaleFreq);
  for (let i = 0; i < numtaps; i++) h[i] /= s;
  return h;
}

/** neurodsp's filter-length rule: `ceil(fs·n_seconds)`, bumped to odd so the filter is type I. */
export function filterLength(fs: number, nSeconds: number): number {
  let n = Math.ceil(fs * nSeconds);
  if (n % 2 === 0) n += 1;
  return n;
}

/** `filter_signal(sig, fs, 'lowpass', fHi, n_seconds=nSeconds)` — the coefficients only. */
export function designLowpass(fs: number, fHi: number, nSeconds: number): Float64Array {
  return firwin(filterLength(fs, nSeconds), fHi, fs);
}

/** `filter_signal(sig, fs, 'bandstop', [lo, hi], n_seconds=nSeconds)` — the coefficients only. */
export function designBandstop(fs: number, range: [number, number], nSeconds: number): Float64Array {
  return firwin(filterLength(fs, nSeconds), range, fs);
}

/**
 * np.convolve(sig, coefs, 'same'): the full convolution trimmed to `sig.length` samples,
 * centred.  For an odd-length FIR that is the symmetric window — output n is the filter
 * centred on input n, so there is no group delay to correct (this is what neurodsp relies on
 * with remove_edges=False; the first/last (M−1)/2 samples are edge-affected).
 */
export function convolveSame(sig: ArrayLike<number>, coefs: ArrayLike<number>): Float64Array {
  const n = sig.length;
  const m = coefs.length;
  const out = new Float64Array(n);
  if (n === 0 || m === 0) return out;
  // numpy centres the 'same' slice at floor((M-1)/2) into the full result
  // (for M > N numpy swaps operands; the demo never does that, so keep the common case)
  const lead = Math.floor((m - 1) / 2);
  for (let i = 0; i < n; i++) {
    const j = i + lead; // index into the full convolution
    let acc = 0;
    const kLo = Math.max(0, j - n + 1);
    const kHi = Math.min(m - 1, j);
    for (let k = kLo; k <= kHi; k++) acc += coefs[k] * sig[j - k];
    out[i] = acc;
  }
  return out;
}

/**
 * The notebook's "Signal Filtering" cell, completed:
 *
 *   sig_low = filter_signal(sig, og_freq, 'lowpass', downsample_freq / 2, n_seconds=0.2, remove_edges=False)
 *   sig_low = scipy.signal.resample(sig_low, len(sig_low) * downsample_freq / og_freq)
 *
 * The anti-alias lowpass is the same FIR (cutoff at the new Nyquist, 0.2 s Hamming).  The
 * notebook then resamples in the frequency domain (scipy.signal.resample); the browser port
 * decimates by an integer `factor` instead — after an identical lowpass the two agree to
 * within the FIR's stop-band leakage, and the decimate is free.  Returns the new signal;
 * the caller's sampling rate becomes fs / factor.
 */
export function lowpassDecimate(sig: ArrayLike<number>, fs: number, factor: number): Float64Array {
  if (!Number.isInteger(factor) || factor < 1) throw new Error("lowpassDecimate: factor must be a positive integer");
  const coefs = designLowpass(fs, fs / factor / 2, 0.2);
  const low = convolveSame(sig, coefs);
  if (factor === 1) return low;
  const out = new Float64Array(Math.ceil(low.length / factor));
  for (let i = 0; i < out.length; i++) out[i] = low[i * factor];
  return out;
}

/** Mains notch: bandstop 58–62 Hz, 0.5 s window (`filter_signal(sig, fs, 'bandstop', (58, 62), n_seconds=0.5)`). */
export function notch60(sig: ArrayLike<number>, fs: number): Float64Array {
  return convolveSame(sig, designBandstop(fs, [58, 62], 0.5));
}

/**
 * Common-average reference: subtract, at every sample, the mean across `channels`.
 * Pass only the channels with good electrode contact — a 40 MΩ electrode would otherwise
 * smear its noise into every other trace.  Returns new arrays; the inputs are untouched.
 */
export function commonAverage(channels: Float32Array[]): Float32Array[] {
  if (channels.length === 0) return [];
  const n = channels[0].length;
  const mean = new Float32Array(n);
  for (const ch of channels) for (let i = 0; i < n; i++) mean[i] += ch[i];
  const inv = 1 / channels.length;
  for (let i = 0; i < n; i++) mean[i] *= inv;
  return channels.map((ch) => {
    const out = new Float32Array(n);
    for (let i = 0; i < n; i++) out[i] = ch[i] - mean[i];
    return out;
  });
}
